---
title: "Stats 531 (Winter 2016) <br>'Analysis of Time Series'"
author: "Instructor: Edward L. Ionides"
output:
  html_document:
    theme: flatly
    toc: yes
csl: ecology.csl
---

------

## Course description

This course gives an introduction to time series analysis using
time domain methods and frequency domain methods. The goal is to
acquire the theoretical and computational skills required to investigate
data collected as a time series. The first half of the course will develop 
classical time series methodology, including auto-regressive moving average (ARMA) models, regression with ARMA errors, and estimation of the spectral density.
The second half of the course will focus on state space model techniques for fitting structured dynamic models to time series data. We will progress from fitting linear, Gaussian dynamic models to fitting nonlinear models for which Monte Carlo methods are required.
Examples will be drawn from ecology, economics, epidemiology, finance and elsewhere.

--------------

## Course information

* Class meets Tu/Th 2:30-4:00 in 1084 East Hall

* Contact information:
    + Office: 453 West Hall 
    + Phone: 647 5457 
    + E-mail: ionides@umich.edu 
    + Web: dept.stat.lsa.umich.edu/~ionides
    + Office hours:  Mon 11:30-12:30; Wed 1:00-2:00. 
* GSI: Dao Nguyen
    + Office hours: Tue 10:00-11:00, Science Learning Center, 1720 Chemistry Building.
    + Computing support: inquire by email, with a detailed description of the problem, what you did, and what error message you obtained.
    + E-mail: nguyenxd@umich.edu
* Textbook: R. Shumway and D. Stoffer ``Time Series Analysis and its Applications'' 3rd edition. Available for free from [David Stoffer's website](www.stat.pitt.edu/stoffer/tsa3/tsa3.pdf)
* Pre-requisites: Stat 426 (Introduction to Theoretical
 Statistics) or equivalent. For review, see ``Mathematical
 Statistics and Data Analysis'' by J. A. Rice. A certain amount
 of basic linear algebra will be required. For review, see 
[www.sosmath.com/matrix/matrix.html](www.sosmath.com/matrix/matrix.html)

-----------

##  Grading

* Weekly homeworks (25\%, due Tuesdays, in class).
* A midterm exam (25\%, in class on Thursday 2/25).
* A midterm project analyzing a time series of your choice using methods covered in the first half of the course (15\%, due Thursday 3/10). 
* A final project analyzing a time series of your choice using methods covered in the entire course (35\%, due Thursday 4/28). 

Discussion of homework problems is encouraged, but solutions must be written up individually.  Direct copying is not acceptable.

Any material taken from any source, such as the internet, must be properly acknowledged. Unattributed copying from any source is plagiarism, and has potentially [serious consequences](http://www.rackham.umich.edu/current-students/policies/academic-policies/section11).


----------

## Class notes

1. [Introduction](intro/intro.html). [(R script)](intro/intro.R)

2. [Definitions and trend estimation by least squares](trend/trend.html). [(R script)](trend/trend.R)

3. [Stationarity, white noise, and some basic time series models](notes3/notes3.html). [(R script)](notes3/notes3.R)

4. [Linear time series models and the algebra of ARMA models](notes4/notes4.html). [(R script)](notes4/notes4.R)

5. [Parameter estimation and model identification for ARMA models](notes5/notes5.html). [(R script)](notes5/notes5.R)

6. [Extending the ARMA model: Seasonality and trend](notes6/notes6.html). [(R script)](notes6/notes6.R)

7. [Introduction to the frequency domain](notes7/notes7.html). [(R script)](notes7/notes7.R)


8. [Smoothing in the time and frequency domains](notes8/notes8.html). [(R script)](notes8/notes8.R)

9. [Introduction to partially observed Markov process models](notes9/notes9.html). [(R script)](notes9/notes9.R)

10. [Case study: An association between unemployment and mortality?](notes10/notes10.html) [(R script)](notes10/notes10.R)

11. [Statistical methodology for nonlinear partially observed Markov process models](notes11/notes11.html). [(R script)](notes11/notes11.R)

12. [Dynamic models and their simulation by Euler’s method](notes12/notes12.html). [(R script)](notes12/notes12.R)

13. [Practical likelihood-based inference for POMP models](notes13/notes13.html). [(R script)](notes13/notes13.R)

--------

## Homework assignments

* [Homework 0](hw/hw00.html), due in class on 1/12. Setting up your computational environment.

* [Homework 1](hw/hw01.html), due in class on 1/19. [Solution](hw/sol01.html).

* [Homework 2](hw/hw02.html), due in class on 1/26. [Solution](hw/sol02.html).

* [Homework 3](hw/hw03.html), due midnight on 2/2. [Solution](hw/sol03.html). See also [Chapter 7.3](http://ionides.github.io/531w16/notes7/notes7.html#some-data-analysis-using-the-frequency-domain).

* [Homework 4](hw/hw04.html), due in class on 2/9. [Solution](hw/sol04.html).

* [Homework 5](hw/hw05.html), due in class on 2/16. [Solution](hw/sol05.html).

* [Homework 6](hw/hw06.html), due in class on 2/23. [Responses](hw/summary06.html).

* [Homework 7](hw/hw07.html), a single slide due midnight on 3/21, for a presentation in class on 3/22 or 3/24.

* [Homework 8](hw/hw08.html), due on 3/29.


------------

## Midterm exam information

* The midterm exam will involve reasoning about a data analysis using the theoretical and computational techniques we have studied in class. 

* The exam may include techniques covered in homeworks 1-5 and will assume familiarity with Chapters 1-10 of the notes. For Chapter 9, you do not need to review algebraic manipulation of state space models beyond what was in homework 5. 

* You should bring to the exam just pens and/or pencils. The exam will be taken without any electronic devices, books or notes.

* The best predictor of the style of the exam may be the following two past papers from a somewhat similar course:

    +  [Midterm exam for Stats531 Winter 2016](exam/w16/mt531w16.pdf). [Solutions](exam/w16/mt531w16sol.pdf).

    +  [Midterm exam for Stats531 Winter 2009](exam/w09/mt531w09.pdf). [Solutions](exam/w09/mt531w09sol.pdf).

    + [Midterm exam for Stats531 Winter 2007](exam/w07/mt531w07.pdf). [Solutions](exam/w07/mt531w07sol.pdf).

## Midterm project

* [Information](midterm_project/midterm_project_info.html)

* [Projects](midterm_project/index.html)

* [Plagiarism and midterm project grades](midterm_project/plagiarism.html)

* [Postscript on plagiarism in the midterm project](midterm_project/postscript_on_plagiarism.html)

---------