---
title: "Homework 4, due in class on Tues 2/9"
author: "Stats 531, Winter 2016"
output:
  html_document:
    theme: flatly
    toc: yes
---

\newcommand\prob{\mathbb{P}}
\newcommand\E{\mathbb{E}}
\newcommand\var{\mathrm{Var}}
\newcommand\cov{\mathrm{Cov}}

-----------

This homework gives you some experience at manipulating models and data in the frequency domain.


--------

**<big>Question 4.1</big>**. 

<b>A</b>. Compute and plot the autocovariance function and the spectral density function of a stationary AR2 model,
$$ X_n =  1.5 X_{n-1} - 0.8X_{n-1} + \epsilon_n,$$
where $\{\epsilon_n\}$ is white noise with $\var(\epsilon_n)=\sigma^2$.
You can use software to do this, or compute by hand. Please explain fully how you carried out your calculation.

<b>B</b>. Compute and plot the autocovariance function and the spectral density function of an MA(2) moving mean,
$$ X_n = \epsilon_{n-2} + \epsilon_{n-1}+\epsilon_n,$$
where $\{\epsilon_n\}$ is white noise with $\var(\epsilon_n)=\sigma^2$.
You can use software to do this, or compute by hand. Please explain fully how you carried out your calculation.


<b>C</b>. Comment briefly on what you find in parts A and B.

**<big>Question 4.2</big>**. Find an estimated spectral density of the sunspot time series in [sunspots.txt](sunspots.txt). Comment on your choice of estimator. Comment on the resulting estimate. These data, as well as some background on the historical and current interest in sunspot activity, are described at [http://solarscience.msfc.nasa.gov/SunspotCycle.shtml](http://solarscience.msfc.nasa.gov/SunspotCycle.shtml).


--------
