\newcommand\prob{\mathbb{P}}
\newcommand\E{\mathbb{E}}
\newcommand\var{\mathrm{Var}}
\newcommand\cov{\mathrm{Cov}}


```{r knitr-opts,include=FALSE,cache=FALSE,purl=FALSE}
library(pomp)
library(knitr)
prefix <- "HW4"
opts_chunk$set(
  progress=TRUE,
  prompt=FALSE,tidy=FALSE,highlight=TRUE,
  strip.white=TRUE,
  warning=FALSE,
  message=FALSE,
  error=FALSE,
  echo=TRUE,
  cache=TRUE,
  cache_extra=rand_seed,
  results='markup',
  fig.show='asis',
  size='small',
  fig.lp="fig:",
  fig.path=paste0("figure/",prefix,"-"),
  cache.path=paste0("cache/",prefix,"-"),
  fig.pos="h!",
  fig.align='center',
  fig.height=4,fig.width=6.83,
  dpi=300,
  dev='png',
  dev.args=list(bg='transparent')
)

set.seed(2050320976)
```
```{r opts,include=FALSE,cache=FALSE}
options(
  keep.source=TRUE,
  encoding="UTF-8"
)
```

<big><big><b>Mini-presentation signup sheet</b></big></big>

Please sign up for either Tuesday or Thursday.

<big><big>

```{r tues_table,echo=FALSE}
require(htmlTable)
htmlTable(cbind(1:10,11:20),
          cgroup = c("Signup for Tuesday March 22 "),
          n.cgroup = c(2),
   align="ll",
  css.cell = "padding-left: .5em; padding-right: 15em;"
)
```


<br>

```{r thur_table,echo=FALSE}
require(htmlTable)
htmlTable(cbind(1:10,11:20),
          cgroup = c("Signup for Thursday March 24 "),
          n.cgroup = c(2),
   align="ll",
  css.cell = "padding-left: .5em; padding-right: 15em;"
)
```

</big></big>
