---
title: "Final project instructions"
author: "Stats 531, Winter 2016"
output:
  html_document:
    theme: flatly
    toc: yes
---

\newcommand\prob{\mathbb{P}}
\newcommand\E{\mathbb{E}}
\newcommand\var{\mathrm{Var}}
\newcommand\cov{\mathrm{Cov}}

-----------


#### Final project outline

Find a time series dataset of your choice. Carry out a time series analysis, taking advantage of what we have learned in this course. It is expected that part of your project will involve a POMP analysis, taking advantage of the methods we have studied in the second half of this semester. 

Although the POMP framework gives plenty of opportunity to develop and analyze relevant models, it involves some potential challenges which we will attempt to anticipate:

1. A common goal of POMP analysis is to connect theory to data, but what if you don't know a theory for the system on which you have data? 

    i. Sometimes, this can be addressed by choice of data. If possible, choose a dataset on a topic for which you know, or are willing to discover, some background theory.

    ii. If you are fairly sure of the data you would like to analyze, but can't find any relevant theory, I'll be happy to help you work something out, in office hours or by email. If you want data from epidemiology or ecology, I can suggest options for you. For other interests, I may or may not have suggestions but can certainly help you look.

    iii. An alternative way in which POMP models can arise is including time-varying parameters in a non-POMP model. 

2. Computational considerations may prevent you analyzing as large a model, or as long a dataset, as you would ideally do. That is fine. Present a smaller, computationally feasible analysis and discuss possible extensions to  your analysis.


To submit your project, write your report as an R markdown (Rmd) file.  Submit the report by midnight on Thursday April 28 as a zip file containing an Rmd file and anything else necessary to allow the grader to render the Rmd file as an html document.

---------

#### Choice of data

 As for the midterm project, the time series should hopefully have at least 100 time points. You can have less, if your interests demand it. Shorter data needs additional care, since model diagnostics and asymptotic approximations become more delicate on small datasets. If your data are longer than, say, 1000 time points, you can subsample if you start having problems working with too much data. 

Time series which you know how to connect to mechanistic hypotheses may be informative to analyze but are harder find online than what we needed for the midterm project. Therefore, I expect more of you to come asking for help identifying a suitable project. One approach to this is for you to spend some time looking online and thinking about what you might like to do, then send me an email with your current thoughts and we can meet in office hours or after class and discuss it further.

----------

#### Expectations for the report

The report will be graded on the same criteria as used for the midterm project. The following descriptions are exactly the same as the midterm report, though we have talked plenty more since then about some [basic Rackham standards](http://www.rackham.umich.edu/current-students/policies/academic-policies/section11#112) on "making references where appropriate". 

* Raising a question. You should explain some background to the data you chose, and give motivation for the reader to appreciate the purpose of your data analysis. 

* Use of appropriate statistical methods.

* Scholarship. Your report should make references where appropriate. The models and methods you use should be fully explained, either by references or within your report. When using a reference to point the reader to descriptions elsewhere, you should provide a brief summary in your own report. Although you will be submitting your source code, you should not expect the reader to study it.

* Reaching a conclusion. You should say what you have concluded, as well as describing things you might have liked to do that were beyond the scope of this midterm project.

* Presentation of data analysis. Focus on a few, carefully explained and justified, figures, tables, statistics and hypothesis tests. You may want to try many things, but only write up evidence supporting how the data help you to get from your question to your conclusions. Including material that is of borderline relevance, or that is not fully explained, makes it harder for the reader to appreciate your analysis.

------------

#### Methodology not covered in class

This class has focused on ARMA and POMP models, two related approaches to time domain analysis of time series. 

Time series topics on which we will spend little or no time include frequency domain analysis of multivariate time series (Shumway and Stoffer, Chapter 7) and time-frequency domain analysis using wavelets (Shumway and Stoffer, Section 4.9). 

If you decide that alternative approaches are particularly relevant for your data, you can use them in your project as a complementary approach to what we have covered in class. 


--------



 